# docker-compose -f stack.yml up
# docker-compose -f stack.yml up -d

version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123456

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
